# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\study\third year\first term\software engineering\Domestic-Animal\profiles.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QLabel{\n"
"font: 16pt \"Purisa\";\n"
"}\n"
"QPushButton{\n"
"color: green;\n"
"background-color: black;\n"
"border: 2px green;\n"
"border-radius: 3px;\n"
"font: 16pt \"Purisa\";\n"
"}\n"
"QRadioButton{\n"
"font: 26pt \"Purisa\";\n"
"}\n"
"QLineEdit{\n"
"font: 26pt \"Purisa\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 221, 71))
        self.label.setObjectName("label")
        self.bt_continue = QtWidgets.QPushButton(self.centralwidget)
        self.bt_continue.setGeometry(QtCore.QRect(630, 30, 111, 31))
        self.bt_continue.setStyleSheet("")
        self.bt_continue.setObjectName("bt_continue")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 80, 771, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lb_feed = QtWidgets.QLabel(self.centralwidget)
        self.lb_feed.setGeometry(QtCore.QRect(240, 10, 371, 71))
        self.lb_feed.setText("")
        self.lb_feed.setObjectName("lb_feed")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Choose a profile: "))
        self.bt_continue.setText(_translate("MainWindow", "Continue"))
