# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Domestic-Animal\Domestic-Animal\launcher\ui\profiles.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:qradialgradient(spread:reflect, cx:0.480198, cy:0.506, radius:0.5, fx:0.955, fy:0.511364, stop:0.401832 rgba(34, 124, 112, 255), stop:1 rgba(136, 164, 124, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame{\n"
"background-color: transparent;\n"
"border: 1px ridge black;\n"
"border-radius: 10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 781, 581))
        self.frame.setStyleSheet("QWidget{\n"
"background-color: transparent;\n"
"}\n"
"QPushButton{\n"
"color: rgb(28, 49, 94);\n"
"border: 2px solid rgb(28, 49, 94);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(230, 226, 195);\n"
"}\n"
"QPushButton::pressed{\n"
"background-color:  rgb(28, 49, 94);\n"
"}\n"
"QToolButton{\n"
"background-color: rgb(136, 164, 124);\n"
"border: 1px solid;\n"
"border-radius: 5px;\n"
"}\n"
"QToolButton::hover{\n"
"background-color: rgb(230, 226, 195);\n"
"}\n"
"QLineEdit{\n"
"color: rgb(28, 49, 94);\n"
"border: 2px groove rgb(28, 49, 94);\n"
"border-radius: 5px;\n"
"}\n"
"QLineEdit::focus{\n"
"background-color: rgb(230, 226, 195);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_continue = QtWidgets.QPushButton(self.frame)
        self.bt_continue.setGeometry(QtCore.QRect(620, 30, 141, 31))
        self.bt_continue.setStyleSheet("")
        self.bt_continue.setObjectName("bt_continue")
        self.lb_feed = QtWidgets.QLabel(self.frame)
        self.lb_feed.setGeometry(QtCore.QRect(230, 10, 371, 71))
        self.lb_feed.setStyleSheet("border: 0px;")
        self.lb_feed.setText("")
        self.lb_feed.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_feed.setObjectName("lb_feed")
        self.label_c = QtWidgets.QLabel(self.frame)
        self.label_c.setGeometry(QtCore.QRect(20, 10, 251, 71))
        self.label_c.setStyleSheet("border: none;")
        self.label_c.setObjectName("label_c")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 80, 761, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_continue.setText(_translate("MainWindow", "Continue"))
        self.label_c.setText(_translate("MainWindow", "Choose a profile: "))
